name: testing application
on:
  workflow_dispatch: {}
  push:
    branches: "*"
    paths:
      - sushil/**

permissions:
  contents: read

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - 'sushil/**'
  build:
    name: pi
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Script
      run: |
        exit 0
  sheild:
    name: di
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Script
      run: |
        python3 sk.py      
